FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir "mcstatus>=13,<14"

COPY app ./app
COPY data ./data

ENV STATUS_HUB_HOST=0.0.0.0
ENV STATUS_HUB_PORT=8080
ENV STATUS_HUB_DB=/app/data/status_hub.db
ENV WIDGET_POLL_INTERVAL=60
ENV MEOWSTATUS_ADMIN_TOKEN=change-me
ENV MEOWSTATUS_ADMIN_PATH=/admin
ENV MEOWSTATUS_AUTH_MAX_ATTEMPTS=5
ENV MEOWSTATUS_AUTH_WINDOW_SEC=60
ENV MEOWSTATUS_AUTH_LOCKOUT_SEC=300

EXPOSE 8080

CMD ["python", "-m", "app.main"]

